backend:
  name: git-gateway  # Must be 'git-gateway', not 'github'
  branch: main      # Your repo's default branch

publish_mode: editorial_workflow  # Optional, enables draft/preview
media_folder: "static/img"
public_folder: "/img"

site_url: https://franklinsquarebarber.netlify.app
display_url: https://franklinsquarebarber.netlify.app

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "about"
    label: "About"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}